id: wp-config-disclosure-fuzzing
info:
  name: WordPress Config Disclosure Fuzzing Template
  author: h0tak88r
  severity: high
  description: Fuzzes for wp-config.PHP and wp-config.php.
http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-config.PHP"
      - "{{BaseURL}}/wp-config.php"
    matchers:
      - type: status
        status:
          - 200
